/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.dto.UserDTO;
import org.example.mapper.UserMapper;
import org.example.model.UserModel;
import org.mapstruct.factory.Mappers;

import java.time.LocalDate;

public class App {

    private static final UserMapper mapper = Mappers.getMapper(UserMapper.class);

    public static void main(String[] args) {
        var model = new UserModel();
        model.setUsername("Caly");
        model.setCode(22);
        model.setBirthday(LocalDate.now().minusYears(20));
        System.out.println(mapper.todto(model));

        var dto = new UserDTO();
        dto.setName("Torres");
        dto.setId(21);
        dto.setBirthday(LocalDate.now().minusYears(10));
        System.out.println(mapper.tomodel(dto));
    }
}
